### ISSUE TITLE
Chapter02. 카프카 환경 구성

### ISSUE THREAD

**Issue by LOG-INFO** [DevSprout/Practice-Kafka-Dev-To-Production#2]

**Comment by LOG-INFO** [comment]
https://gajy.tistory.com/50 참고하여 Docker + Minikube + Bitnami Helm Chart로 구성

#### values.yaml
```yaml
replicaCount: 3
defaultReplicationFactor: 3
offsetsTopicReplicationFactor: 3
transactionStateLogReplicationFactor: 3
persistence:
  enabled: true

zookeeper:
  replicaCount: 3

externalAccess:
  enabled: true
  service:
    type: NodePort
    nodePorts:
      - 30001
      - 30002
      - 30003
    useHostIPs: true
    domain: "192.168.1.1"
```
